#!/usr/bin/env python
#-*- encoding: utf-8 -*-

import requests
import time
import re
from lxml import etree
import pandas as pd
import csv
from bs4 import BeautifulSoup
  
def getList():
    start_url = 'https://book.douban.com/tag/青春?&type=T&start={}'
    i = 1
    infoList = []
    while i < 6: 
        url.format(i)
        kv = {'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 
         'Accept': '*/*', 'User-Agent': 'Mozilla/5.0'}
        r = requests.get(url,headers=kv) 
        selector = etree.HTML(r.text)
        i += 1
        informations = selector.xpath('.//ul[@class="subject-list"]/li')
        for inf in informations: 
            info_bookname = inf.xpath('normalize-space(.//div[@class="info"]/h2/a/@title)')
            info_str = inf.xpath('normalize-space(.//div[@class="pub"]/text())')#[0].replaceAll("\r|\n", "")
            info_author = ''
            strlist = info_str.split('/')
            i = 0
            index = 0
            while i < 4:
                if("出版社" in strlist[i]):
                    index = i
                i += 1
            j = 0
            while j < index:
                info_author += strlist[j]
                j += 1      
            info_publisher = strlist[index]
            info_price = strlist[index+1].replace('元','')
            info_score = inf.xpath('normalize-space(.//span[@class="rating_nums"]/text())')
            info_commentsnum = inf.xpath('normalize-space(.//span[@class="pl"]/text())')
            infoList.append([info_bookname,info_author,info_publisher,info_price,info_score,info_commentsnum])
        time.sleep(20)
    return infoList

def listToCsv(list):
    df = pd.DataFrame(list,columns=['书名','作者','出版社','售价','豆瓣评分','评论数量'])
    file = open("pachong.csv", "w", encoding='utf-8')
    df.to_csv(file, line_terminator="\n", index=False)
    file.close()
   # print(df)
    csv_reader=csv.reader(open('pachong.csv','r',encoding='utf-8'))
    for row in csv_reader:
        print(row)
 
 def main():
    List = getList() 
    listToCsv(List)
 
 
if __name__=='__main__': 
	main()
